// src/components/ProfileContent.svelte
<script lang="ts">
	import Camera from '$components/icons/Camera.svelte';
	import Github from '$components/icons/Github.svelte';
	import LinkedIn from '$components/icons/LinkedIn.svelte';
	import Archive from '$components/icons/Archive.svelte';
	import ThemeToggle from '$components/ThemeToggle.svelte';

	const links = [
		{
			href: 'https://barnsworthburning.net/creators/rec97tRUYZBhAs6rZ',
			label: 'Commonplace',
			icon: Archive,
		},
		{ href: 'https://github.com/Aias', label: 'Github', icon: Github },
		{ href: 'https://www.linkedin.com/in/nick-trombley/', label: 'LinkedIn', icon: LinkedIn },
		{ href: 'https://glass.photo/barnsworthburning', label: 'Photography', icon: Camera },
	];
</script>

<div class="profile">
	<section class="info">
		<header class="header">
			<h1>Nicholas Trombley</h1>
			<p class="secondary">
				<em>Digital designer-builder.</em>
			</p>
		</header>
		<nav class="site-nav">
			<ul class="external-links">
				{#each links as link}
					{@const IconComponent = link.icon}
					<li>
						<a class="link" href={link.href} target="_blank">
							<IconComponent />
							<span class="label">{link.label}</span>
						</a>
					</li>
				{/each}
			</ul>
		</nav>
		<ThemeToggle />
	</section>
	<section class="personal-statement">
		<p>
			<strong>
				Craft-driven creator of digital tools with a mind for information design, knowledge
				management, and systems thinking.
			</strong>
		</p>
		<p>
			Over a decade of experience building useful software at all scales, from enterprise-grade
			solutions to bespoke artifacts of the small, personal web. Currently at <a
				href="https://withremark.com"
				target="_blank"
				rel="noopener noreferrer">Remark</a
			>.
		</p>
	</section>
</div>

<style>
	.profile {
		background-color: var(--widget-container);
		border: 3px double var(--widget-border);
		padding: 2.5rem 3.5rem;
		font-size: 1.25em;
		display: flex;
		align-items: stretch;
		justify-content: center;
		gap: 2rem;
		z-index: 1;
		overflow: hidden;
		width: 100%;
		height: 100%;
		position: relative;
	}

	.info {
		flex: 1;
		display: flex;
		flex-direction: column;
		justify-content: space-evenly;
		gap: 1em;

		& :global(.theme-toggle) {
			position: absolute;
			inset-inline-end: 1rem;
			inset-block-end: 1rem;
		}
	}

	.personal-statement {
		flex: 0 0 25rem;
		text-align: justify;
		display: flex;
		flex-direction: column;
		justify-content: center;
		gap: 1em;
	}

	.site-nav {
		container-type: inline-size;
		container-name: nav;
	}

	@container root (width <= 64rem) {
		/* TODO: Change this to fixed, currently broken in Safari. 
		   https://frontendmasters.com/blog/containers-context/ */
		/* .info :global(.theme-toggle) {
			position: fixed;
			font-size: 1.75rem;
		} */

		@container profile (width <= 58rem) {
			.profile {
				display: grid;
				grid-template-areas:
					'header'
					'statement'
					'nav';
				gap: 1.5rem;
				text-align: center;
				border-inline: none;
				border-block-start: none;
				padding-inline: 2rem;
			}

			.info {
				display: contents;
			}

			.header {
				grid-area: header;
			}

			.personal-statement {
				grid-area: statement;
				justify-content: flex-start;
				gap: 0.75rem;
				text-align: center;
				text-wrap: balance;
			}

			.site-nav {
				grid-area: nav;
				flex-direction: row;

				.external-links {
					display: flex;
					flex-wrap: wrap;
					flex-direction: row;
					justify-content: center;
					column-gap: 1.5rem;
				}
			}

			@container nav (width <= 40rem) {
				li:last-child {
					display: none;
				}
			}
		}
	}
</style>

// src/components/ProfileContent.tsx
import * as stylex from '@stylexjs/stylex';
import { colors, fonts, space } from '../styles/tokens.stylex';
import type { Theme } from '../theme';
import { SiteIcon } from './SiteIcon';
import { ThemeToggle } from './ThemeToggle';

const MOBILE = '@container portfolio (max-width: 64rem)';
const styles = stylex.create({
	root: {
		position: 'relative',
		display: 'grid',
		gridTemplateColumns: { default: 'minmax(0, 1fr) 25rem', [MOBILE]: '1fr' },
		alignItems: 'center',
		gap: { default: space[32], [MOBILE]: space[24] },
		width: '100%',
		height: { default: '100%', [MOBILE]: 'auto' },
		paddingBlock: { default: '2.5rem', [MOBILE]: space[48] },
		paddingInline: { default: '3.5rem', [MOBILE]: space[32] },
		borderWidth: { default: 3, [MOBILE]: 0 },
		borderBottomWidth: 3,
		borderStyle: 'double',
		borderColor: colors.border,
		backgroundColor: colors.container,
		color: colors.primary,
		fontFamily: fonts.serif,
		fontSize: '1.25rem',
		lineHeight: space[32]
	},
	info: { display: { default: 'grid', [MOBILE]: 'contents' }, gap: space[32], minWidth: 0 },
	header: { minWidth: 0, textAlign: { default: 'start', [MOBILE]: 'center' } },
	name: {
		fontSize: '2.625rem',
		lineHeight: space[64],
		whiteSpace: 'nowrap',
		textOverflow: 'ellipsis',
		overflow: 'hidden'
	},
	tagline: { color: colors.secondary, fontStyle: 'italic' },
	links: {
		display: 'flex',
		flexDirection: { default: 'column', [MOBILE]: 'row' },
		flexWrap: 'wrap',
		justifyContent: { default: 'start', [MOBILE]: 'center' },
		columnGap: space[24]
	},
	nav: { order: { default: 0, [MOBILE]: 2 }, minWidth: 0 },
	link: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: space[8],
		color: colors.themeText,
		textDecoration: 'underline',
		textUnderlineOffset: '0.125em'
	},
	statement: {
		display: 'flex',
		flexDirection: 'column',
		gap: space[32],
		minWidth: 0,
		textAlign: { default: 'justify', [MOBILE]: 'center' }
	},
	strong: { fontWeight: 700 },
	theme: { position: 'absolute', insetInlineEnd: space[16], insetBlockEnd: space[16] }
});

const links = [
	{
		href: 'https://barnsworthburning.net/creators/rec97tRUYZBhAs6rZ',
		label: 'Commonplace',
		icon: 'archive'
	},
	{ href: 'https://github.com/Aias', label: 'Github', icon: 'github' },
	{ href: 'https://www.linkedin.com/in/nick-trombley/', label: 'LinkedIn', icon: 'linkedin' },
	{ href: 'https://glass.photo/barnsworthburning', label: 'Photography', icon: 'camera' }
] satisfies { href: string; label: string; icon: 'archive' | 'github' | 'linkedin' | 'camera' }[];

export function ProfileContent({ theme }: { theme: Theme }) {
	return (
		<section {...stylex.props(styles.root)} aria-label="About Nicholas Trombley">
			<div {...stylex.props(styles.info)}>
				<header {...stylex.props(styles.header)}>
					<h1 {...stylex.props(styles.name)}>Nicholas Trombley</h1>
					<p {...stylex.props(styles.tagline)}>Digital designer-builder.</p>
				</header>
				<nav {...stylex.props(styles.nav)} aria-label="Find me online">
					<ul {...stylex.props(styles.links)}>
						{links.map((link) => (
							<li key={link.href}>
								<a
									{...stylex.props(styles.link)}
									href={link.href}
									target="_blank"
									rel="noopener noreferrer"
								>
									<SiteIcon name={link.icon} />
									{link.label}
								</a>
							</li>
						))}
					</ul>
				</nav>
			</div>
			<div {...stylex.props(styles.statement)}>
				<p {...stylex.props(styles.strong)}>
					Craft-driven creator of digital tools with a mind for information design, knowledge
					management, and systems thinking.
				</p>
				<p>
					Over a decade of experience building useful software at all scales, from enterprise-grade
					solutions to bespoke artifacts of the small, personal web. Currently at{' '}
					<a
						{...stylex.props(styles.link)}
						href="https://remark.ai/"
						target="_blank"
						rel="noopener noreferrer"
					>
						Remark
					</a>
					.
				</p>
			</div>
			<div {...stylex.props(styles.theme)}>
				<ThemeToggle theme={theme} />
			</div>
		</section>
	);
}
