// src/components/ThemeToggle.tsx
import * as stylex from '@stylexjs/stylex';
import { colors, radius, space } from '../styles/tokens.stylex';
import { toggleTheme, type Theme } from '../theme';
import { SiteIcon } from './SiteIcon';

const styles = stylex.create({
	button: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: space[32],
		height: space[32],
		color: colors.accent,
		backgroundColor: { 'default': colors.tint, ':hover': colors.tone },
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: colors.border,
		borderRadius: radius.small
	},
	icon: { display: 'flex' },
	hidden: { display: 'none' },
	systemSun: { display: { 'default': 'flex', '@media (prefers-color-scheme: dark)': 'none' } },
	systemMoon: { display: { 'default': 'none', '@media (prefers-color-scheme: dark)': 'flex' } }
});

export function ThemeToggle({ theme }: { theme: Theme }) {
	return (
		<button
			{...stylex.props(styles.button)}
			type="button"
			aria-label="Toggle color theme"
			title="Toggle color theme"
			onClick={toggleTheme}
		>
			<span
				{...stylex.props(
					styles.icon,
					theme === 'dark' && styles.hidden,
					theme === 'system' && styles.systemSun
				)}
			>
				<SiteIcon name="sun" />
			</span>
			<span
				{...stylex.props(
					styles.icon,
					theme === 'light' && styles.hidden,
					theme === 'system' && styles.systemMoon
				)}
			>
				<SiteIcon name="moon" />
			</span>
		</button>
	);
}

// src/components/ThemeToggle.svelte
<script lang="ts">
	import Moon from '$components/icons/Moon.svelte';
	import Sun from '$components/icons/Sun.svelte';
	function handleThemeChange() {
		const htmlNode = document.documentElement;
		let theme: 'light' | 'dark';

		if (htmlNode.classList.contains('light')) {
			htmlNode.classList.remove('light');
			htmlNode.classList.add('dark');
			theme = 'dark';
		} else if (htmlNode.classList.contains('dark')) {
			htmlNode.classList.remove('dark');
			htmlNode.classList.add('light');
			theme = 'light';
		} else {
			const userPreference = window.matchMedia('(prefers-color-scheme: dark)').matches
				? 'light'
				: 'dark';
			htmlNode.classList.add(userPreference);
			theme = userPreference;
		}

		// Set the theme cookie with a long expiration (1 year)
		document.cookie = `theme=${theme};path=/;max-age=31536000;SameSite=Lax`;
	}
</script>

<div class="theme-toggle">
	<button type="button" aria-label="Toggle theme" title="Toggle theme" onclick={handleThemeChange}
		><Moon /><Sun /></button
	>
</div>

<style>
	.theme-toggle {
		border-radius: 0.125em;
		display: inline-flex;
		background-color: var(--widget-container);
	}
	button {
		color: var(--widget-accent);
		border: 1px solid var(--widget-border);
		border-radius: 0.125em;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		gap: 0.5em;
		padding: 0.25em;
		cursor: pointer;
		transition: background-color 0.15s ease-in-out;
		background-color: var(--widget-tint);
		&:hover {
			background-color: var(--widget-tone);
		}
	}
</style>
